apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-staging

resources:
  - ../../base

# Staging runs a smaller footprint.
replicas:
  - name: demo-app
    count: 2

images:
  - name: ghcr.io/asamahamed/gitops-demo-app
    newTag: staging

commonLabels:
  environment: staging
