apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-production

resources:
  - ../../base

# Production runs more replicas for higher availability.
replicas:
  - name: demo-app
    count: 4

images:
  - name: ghcr.io/asamahamed/gitops-demo-app
    newTag: production

commonLabels:
  environment: production
